production:
  adapter:    mysql2
  database:   <%= ENV['DATABASE_NAME'] %>
  host:       <%= ENV['MYSQL_SERVICE_HOST'] %>
  port:       3306
  username:   <%= ENV['DATABASE_USER'] %>
  password:   <%= ENV['DATABASE_PASSWORD'] %>
  encoding:   utf8
  pool:       30